create sequence hibernate_sequence start 1 increment 1;

create table article (
    id int8 not null,
    created_at date,
    status varchar(255) not null,
    text varchar(2048) not null,
    title varchar(255) not null,
    updated_at date,
    user_id int8 not null,
    primary key (id)
);

create table article_tags (
    article_id int8 not null,
    tag_id int8 not null,
    primary key (article_id, tag_id)
);

create table comment (
    id int8 not null,
    created_at date,
    message varchar(255) not null,
    article_id int8,
    user_id int8 not null,
    primary key (id)
);

create table roles (
    id int8 generated by default as identity,
    created timestamp,
    status varchar(255),
    updated timestamp,
    name varchar(255),
    primary key (id)
);

create table tag (
    id int8 not null,
    name varchar(255) not null,
    primary key (id)
);

create table user_roles (
    user_id int8 not null,
    role_id int8 not null,
    primary key (user_id, role_id)
);

create table users (
    id int8 generated by default as identity,
    created timestamp,
    status varchar(255) not null,
    updated timestamp,
    email varchar(255) not null,
    first_name varchar(255),
    last_name varchar(255),
    password varchar(255) not null,
    username varchar(255) not null,
    primary key (id)
);

alter table if exists article
    add constraint article_user_fk
    foreign key (user_id) references users;

alter table if exists article_tags
    add constraint article_tags_tag_fk
    foreign key (tag_id) references tag;

alter table if exists article_tags
    add constraint article_tags_article_fk
    foreign key (article_id) references article;

alter table if exists comment
    add constraint comment_article_fk
    foreign key (article_id) references article;

alter table if exists comment
    add constraint comment_user_fk
    foreign key (user_id) references users;

alter table if exists user_roles
    add constraint user_roles_role_fk
    foreign key (role_id) references roles;

alter table if exists user_roles
    add constraint user_roles_user_fk
    foreign key (user_id) references users;